version: "3.3"

services:
  tracking_server:
    restart: always
    image: mlflow_server
    container_name: mlflow_server
    build: 
      context: ./server
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    expose:
      - "5000"
    ports:
      - "${MLFLOW_PORT}:5000"
    volumes:
      - ./server/container-data/backend-store:/backend-store
      - ./server/container-data/mlartifacts:/mlartifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///backend-store/sqlite.db
      --host 0.0.0.0
  
  jupyter_lab:
    restart: always
    image: jupyter_lab
    container_name: jupyter_lab
    build: 
      context: ./jupyter
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    ports:
      - "${JUPYTER_PORT}:8888"
    volumes:
      - ./jupyter:/jupyterlab
    command: >
      jupyter lab 
      --ip 0.0.0.0 
      --port 8888 
      --allow-root 
      --NotebookApp.token=${JUPYTER_TOKEN}


